### ISSUE TITLE
total AS events output just contain intron_retention 

### ISSUE THREAD

**Issue by wanghuiyuan** [qqwang-berkeley/JUM#16]
total AS events output just contain intron_retention(1062). All other AS events is 0. such as A3SS A5SS MXE and cassette_exon

**Comment by qqwang-berkeley** [comment]
Hi,

Would you show me the commands (parameters) you used, how many input samples you have (under which condition) and the sequencing depth of the samples?

**Comment by qqwang-berkeley** [comment]
OK.  I need the following things from you:
1) When you run the JUM scripts, were there any error messages?
2) Can you send me the "ls -l -t" results in the folder *temp_JUM_A_run*
3) Can you send me the "ls -l -t" results in the folder *JUM_diff*
4) Can you send me the "ls -l -t" results in the folder
*temp_JUM_B_run_pvalue_1*
5) Can you send me the "ls -l -t" results in the folder *temp_JUM_C_run*

2)-4) is for me to check the temporary files generated during each JUM
scripts.

**Comment by wanghuiyuan** [comment]
Hi
  actually, there are no error messages when I run the JUM_A.sh in the first step. But all intersect_short_intron2 files are zero in temp_JUM_A_run. Is that normal？
-rw-rw-r-- 1 lfgu lfgu    0 Aug  9 23:50 c1_rep1Aligned.out_intersect_short_intron2.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 00:01 c1_rep1Aligned.out_intersect_short_intron2_chr_coor.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 00:01 c1_rep1Aligned.out_intersect_short_intron2_count_table
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 00:01 c1_rep1Aligned.out_intersect_short_intron2_edited.txt

-rw-rw-r-- 1 lfgu lfgu    0 Aug  9 23:50 c1_rep2Aligned.out_intersect_short_intron2.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 00:01 c1_rep2Aligned.out_intersect_short_intron2_chr_coor.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 00:01 c1_rep2Aligned.out_intersect_short_intron2_count_table
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 00:01 c1_rep2Aligned.out_intersect_short_intron2_edited.txt

-rw-rw-r-- 1 lfgu lfgu    0 Aug  9 23:52 c2_rep1Aligned.out_intersect_short_intron2.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 00:01 c2_rep1Aligned.out_intersect_short_intron2_chr_coor.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 00:01 c2_rep1Aligned.out_intersect_short_intron2_count_table
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 00:01 c2_rep1Aligned.out_intersect_short_intron2_edited.txt

-rw-rw-r-- 1 lfgu lfgu    0 Aug  9 23:48 c2_rep2Aligned.out_intersect_short_intron2.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 00:01 c2_rep2Aligned.out_intersect_short_intron2_chr_coor.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 00:01 c2_rep2Aligned.out_intersect_short_intron2_count_table
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 00:01 c2_rep2Aligned.out_intersect_short_intron2_edited.txt

All files in *JUM_diff* are normal
-rw-rw-r-- 1 lfgu lfgu 9.8M Aug 10 02:06 AS_differential.txt
drwxrwxr-x 3 lfgu lfgu 8.0K Aug 10 02:56 FINAL_JUM_OUTPUT_pvalue_1
-rw-rw-r-- 1 lfgu lfgu 1.5M Aug  9 20:06 UNION_junc_coor_with_junction_ID_more_than_5_read_in_at_least_2_samples.txt
-rw-rw-r-- 1 lfgu lfgu 365M Aug 10 00:01 c1_rep1Aligned.out_coverage.bed
-rw-rw-r-- 1 lfgu lfgu 1.3M Aug 10 00:03 c1_rep1_combined_count.txt
-rw-rw-r-- 1 lfgu lfgu 358M Aug 10 00:01 c1_rep2Aligned.out_coverage.bed
-rw-rw-r-- 1 lfgu lfgu 1.3M Aug 10 00:03 c1_rep2_combined_count.txt
-rw-rw-r-- 1 lfgu lfgu 430M Aug 10 00:01 c2_rep1Aligned.out_coverage.bed
-rw-rw-r-- 1 lfgu lfgu 1.3M Aug 10 00:03 c2_rep1_combined_count.txt
-rw-rw-r-- 1 lfgu lfgu 402M Aug  9 23:59 c2_rep2Aligned.out_coverage.bed
-rw-rw-r-- 1 lfgu lfgu 1.3M Aug 10 00:03 c2_rep2_combined_count.txt
-rw-rw-r-- 1 lfgu lfgu 7.1M Aug 10 00:02 combined_AS_JUM.gff
-rw-rw-r-- 1 lfgu lfgu 1.9K Aug 10 02:03 errorFile.Rout
-rw-rw-r-- 1 lfgu lfgu   79 Aug 10 01:53 experiment_design.txt
-rw-rw-r-- 1 lfgu lfgu 843K Aug  9 20:06 more_than_5_profiled_total_AS_event_junction_first_processing_for_JUM_reference_building.txt
-rw-rw-r-- 1 lfgu lfgu  214 Aug 10 02:00 outputFile.Rout
drwxrwxr-x 4 lfgu lfgu  12K Aug 10 02:51 temp_JUM_B_run_pvalue_1


there are no error messages when I run the R_script_JUM.R In the second step. All files in *JUM_diff* are normal
-rw-rw-r-- 1 lfgu lfgu 9.8M Aug 10 02:06 AS_differential.txt
drwxrwxr-x 3 lfgu lfgu 8.0K Aug 10 02:56 FINAL_JUM_OUTPUT_pvalue_1
-rw-rw-r-- 1 lfgu lfgu 1.5M Aug  9 20:06 UNION_junc_coor_with_junction_ID_more_than_5_read_in_at_least_2_samples.txt
-rw-rw-r-- 1 lfgu lfgu 365M Aug 10 00:01 c1_rep1Aligned.out_coverage.bed
-rw-rw-r-- 1 lfgu lfgu 1.3M Aug 10 00:03 c1_rep1_combined_count.txt
-rw-rw-r-- 1 lfgu lfgu 358M Aug 10 00:01 c1_rep2Aligned.out_coverage.bed
-rw-rw-r-- 1 lfgu lfgu 1.3M Aug 10 00:03 c1_rep2_combined_count.txt
-rw-rw-r-- 1 lfgu lfgu 430M Aug 10 00:01 c2_rep1Aligned.out_coverage.bed
-rw-rw-r-- 1 lfgu lfgu 1.3M Aug 10 00:03 c2_rep1_combined_count.txt
-rw-rw-r-- 1 lfgu lfgu 402M Aug  9 23:59 c2_rep2Aligned.out_coverage.bed
-rw-rw-r-- 1 lfgu lfgu 1.3M Aug 10 00:03 c2_rep2_combined_count.txt
-rw-rw-r-- 1 lfgu lfgu 7.1M Aug 10 00:02 combined_AS_JUM.gff
-rw-rw-r-- 1 lfgu lfgu 1.9K Aug 10 02:03 errorFile.Rout
-rw-rw-r-- 1 lfgu lfgu   79 Aug 10 01:53 experiment_design.txt
-rw-rw-r-- 1 lfgu lfgu 843K Aug  9 20:06 more_than_5_profiled_total_AS_event_junction_first_processing_for_JUM_reference_building.txt
-rw-rw-r-- 1 lfgu lfgu  214 Aug 10 02:00 outputFile.Rout
drwxrwxr-x 4 lfgu lfgu  12K Aug 10 02:51 temp_JUM_B_run_pvalue_1

when I run the JUM_B.sh In the third step. some files in temp_JUM_B_run_pvalue_1 are abnormal

-rw-rw-r-- 1 lfgu lfgu 6.9M Aug 10 02:47 AS_differential_JUM_output.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 02:51 AS_differential_JUM_output_total_MXE.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 02:51 AS_differential_JUM_output_total_cassette_exon.txt
-rw-rw-r-- 1 lfgu lfgu 1.7M Aug 10 02:51 AS_differential_JUM_output_total_mixed.txt
-rw-rw-r-- 1 lfgu lfgu 9.8M Aug 10 02:47 AS_differential_pvalue_1.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 02:51 AS_differential_pvalue_1_A3SS_event_AS_structure_list.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 02:51 AS_differential_pvalue_1_A5SS_event_AS_structure_list.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 02:51 AS_differential_pvalue_1_MXE_AS_event_list.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 02:51 AS_differential_pvalue_1_cassette_exon_AS_event_list.txt
-rw-rw-r-- 1 lfgu lfgu  20K Aug 10 02:50 AS_differential_pvalue_1_long_intron_retention_passing_filter_combined_list.txt
-rw-rw-r-- 1 lfgu lfgu  64K Aug 10 02:51 AS_differential_pvalue_1_mixed_AS_event_list.txt
-rw-rw-r-- 1 lfgu lfgu 190K Aug 10 02:47 AS_differential_pvalue_1_non_intron_retention_AS_structure_list.txt
-rw-rw-r-- 1 lfgu lfgu  20K Aug 10 02:50 AS_differential_pvalue_1_valid_long_intron_retention_list.txt
-rw-rw-r-- 1 lfgu lfgu 8.2K Aug 10 02:47 AS_differential_pvalue_1_valid_short_intron_retention_list.txt
-rw-rw-r-- 1 lfgu lfgu  20K Aug 10 02:50 AS_differential_total_long_intron_retention_passing_filter_combined_list.txt
-rw-rw-r-- 1 lfgu lfgu  20K Aug 10 02:50 AS_differential_total_valid_long_intron_retention_list.txt
-rw-rw-r-- 1 lfgu lfgu 8.2K Aug 10 02:47 AS_differential_total_valid_short_intron_retention_list.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 02:50 MXE_coordinate_sorted.bed
-rw-rw-r-- 1 lfgu lfgu 365M Aug 10 02:48 c1_rep1Aligned.out_coverage_sorted.bed
-rw-rw-r-- 1 lfgu lfgu  85M Aug 10 02:48 c1_rep1_coverage_temp_long_intron_overlap_pvalue_1.txt
-rw-rw-r-- 1 lfgu lfgu  85M Aug 10 02:49 c1_rep1_coverage_temp_long_intron_overlap_total.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 02:50 c1_rep1_coverage_temp_total_MXE_intersect.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 02:50 c1_rep1_coverage_temp_total_cassette_intersect.txt
-rw-rw-r-- 1 lfgu lfgu  82K Aug 10 02:49 c1_rep1_long_intron_retention_screening_pvalue_1.txt
-rw-rw-r-- 1 lfgu lfgu  82K Aug 10 02:50 c1_rep1_long_intron_retention_screening_total.txt
-rw-rw-r-- 1 lfgu lfgu 312M Aug 10 02:48 c1_rep1_temp_long_intron_retention_junction_coordinate_with_read_num_pvalue_1.txt
-rw-rw-r-- 1 lfgu lfgu 312M Aug 10 02:50 c1_rep1_temp_long_intron_retention_junction_coordinate_with_read_num_total.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 02:50 c1_rep1_temp_total_MXE_coordinate_with_read_num_per_ID.txt
-rw-rw-r-- 1 lfgu lfgu    5 Aug 10 02:50 c1_rep1_temp_total_MXE_with_indicator.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 02:50 c1_rep1_temp_total_cassette_coordinate_with_read_num_per_ID.txt
-rw-rw-r-- 1 lfgu lfgu    5 Aug 10 02:50 c1_rep1_temp_total_cassette_with_indicator.txt
-rw-rw-r-- 1 lfgu lfgu  18K Aug 10 02:49 c1_rep1_valid_long_intron_retention_event_list_pvalue_1.txt
-rw-rw-r-- 1 lfgu lfgu  18K Aug 10 02:50 c1_rep1_valid_long_intron_retention_event_list_total.txt
-rw-rw-r-- 1 lfgu lfgu    1 Aug 10 02:50 c1_rep1_valid_total_MXE_event_ID.txt
-rw-rw-r-- 1 lfgu lfgu    1 Aug 10 02:50 c1_rep1_valid_total_cassette_exon_event_ID.txt
-rw-rw-r-- 1 lfgu lfgu 358M Aug 10 02:48 c1_rep2Aligned.out_coverage_sorted.bed
-rw-rw-r-- 1 lfgu lfgu  82M Aug 10 02:48 c1_rep2_coverage_temp_long_intron_overlap_pvalue_1.txt
-rw-rw-r-- 1 lfgu lfgu  82M Aug 10 02:49 c1_rep2_coverage_temp_long_intron_overlap_total.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 02:50 c1_rep2_coverage_temp_total_MXE_intersect.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 02:50 c1_rep2_coverage_temp_total_cassette_intersect.txt
-rw-rw-r-- 1 lfgu lfgu  82K Aug 10 02:49 c1_rep2_long_intron_retention_screening_pvalue_1.txt
-rw-rw-r-- 1 lfgu lfgu  82K Aug 10 02:50 c1_rep2_long_intron_retention_screening_total.txt
-rw-rw-r-- 1 lfgu lfgu 312M Aug 10 02:48 c1_rep2_temp_long_intron_retention_junction_coordinate_with_read_num_pvalue_1.txt
-rw-rw-r-- 1 lfgu lfgu 312M Aug 10 02:49 c1_rep2_temp_long_intron_retention_junction_coordinate_with_read_num_total.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 02:50 c1_rep2_temp_total_MXE_coordinate_with_read_num_per_ID.txt
-rw-rw-r-- 1 lfgu lfgu    5 Aug 10 02:50 c1_rep2_temp_total_MXE_with_indicator.txt
-rw-rw-r-- 1 lfgu lfgu    0 Aug 10 02:50 c1_rep2_temp_total_cassette_coordinate_with_read_num_per_ID.txt
-rw-rw-r-- 1 lfgu lfgu    5 Aug 10 02:50 c1_rep2_temp_total_cassette_with_indicator.txt
-rw-rw-r-- 1 lfgu lfgu  18K Aug 10 02:49 c1_rep2_valid_long_intron_retention_event_list_pvalue_1.txt
-rw-rw-r-- 1 lfgu lfgu  18K Aug 10 02:50 c1_rep2_valid_long_intron_retention_event_list_total.txt
-rw-rw-r-- 1 lfgu lfgu    1 Aug 10 02:50 c1_rep2_valid_total_MXE_event_ID.txt
-rw-rw-r-- 1 lfgu lfgu    1 Aug 10 02:50 c1_rep2_valid_total_cassette_exon_event_ID.txt

Thanks!

**Comment by qqwang-berkeley** [comment]
If all intersect_short_intron2 files are zero from JUM_A.sh that is fine.
It just means that there were no super short intron retention events in
your sample.

I can help you debug the JUM_B.sh step.
1) Could you dropbox or google drive share with me the JUM_diff folder
(without the temp_JUM_B_run_pvalue_1 and FINAL_JUM_OUTPUT_pvalue_1
subdirectories).  Basically, I am going to run JUM_B.sh on my end on your
files and see why AS events other than IR were empty.  You can share your
folder with my email at: qingqing_wang@berkeley.edu.
2) Could you send the two files:  errorFile.Rout and outputFile.Rout?
These will record detailed information about running the Rscript step.

It is probably not something serious.  Just need some checking.
