### ISSUE TITLE
Can't open perl script "/prepare_count_file_after_STAR_2_pass_mapping.pl": No such file or directory

### ISSUE THREAD

**Issue by LOYON2019** [qqwang-berkeley/JUM#19]
Hi, I got this issue, could you know how to figure out this? thank you.
I use the new version of JUM-JUM_v2.0.2. 
working fold is under fastq, JUM is also under fastq.

root@debian:/mnt/hgfs/rawdata/fastq/N2F# bash ../JUM/JUM_2-2.sh ../JUM 6 3 N2F
Can't open perl script "/prepare_count_file_after_STAR_2_pass_mapping.pl": No such file or directory

**Comment by LOYON2019** [comment]
root@debian:/mnt/hgfs/rawdata/fastq/JUM# ls -l -t
total 103
drwxrwxrwx 1 root root 28672 Jan 16 13:08 bin
-rwxrwxrwx 1 root root   577 Jul 14  2018 JUM_2-1.sh
-rwxrwxrwx 1 root root  2444 Jul 14  2018 JUM_2-2.sh
-rwxrwxrwx 1 root root 17637 Jul 14  2018 JUM_2-3.sh
-rwxrwxrwx 1 root root 16625 Jul 14  2018 JUM_3.sh
-rwxrwxrwx 1 root root 10345 Jul 14  2018 JUM_4.sh
-rwxrwxrwx 1 root root  1070 Jul 14  2018 LICENSE
-rwxrwxrwx 1 root root 24045 Jul 14  2018 Old JUM manual for 1.3.7-1.3.11
-rwxrwxrwx 1 root root  1409 Jul 14  2018 README.md
root@debian:/mnt/hgfs/rawdata/fastq/JUM#

**Comment by qqwang-berkeley** [comment]
I see what is going on.

You need to download from the *JUM_2.0.2.tar.gz* link (the one marked with
31.5KB) on the release page, NOT the Source code (zip) NOR Source code
(tar.gz).

Something is weird. The three links should give you the same folder but the
latter two did not give the correct version. I will fix it.

But at the same time, try downloading JUM2.0.2 again with the correct link
and I think you should be all set.

**Comment by LOYON2019** [comment]
I got the same issue after download the JUM_2.0.2.tar.gz. however, I do see the file "prepare_count_file_after_STAR_2_pass_mapping.pl" in my JUM folder.

root@debian:/mnt/hgfs/rawdata/fastq# bash JUM/JUM_2-1.sh
root@debian:/mnt/hgfs/rawdata/fastq/N2F# bash /mnt/hgfs/rawdata/fastq/JUM/JUM_2-2.sh /mnt/hgfs/rawdata/fastq/JUM 6 3 N2F
Can't open perl script "/prepare_count_file_after_STAR_2_pass_mapping.pl": No such file or directory

**Comment by LOYON2019** [comment]
root@debian:/mnt/hgfs/rawdata/fastq/JUM# ls -l -t
total 215
-rwxrwxrwx 1 root root  2450 Jul 25 19:18 JUM_2-2.sh
-rwxrwxrwx 1 root root 10367 Jul 25 19:17 JUM_C.sh
-rwxrwxrwx 1 root root 20102 Jul 25 19:10 JUM_A.sh
-rwxrwxrwx 1 root root 19729 Jul 25 19:08 JUM_B.sh
-rwxrwxrwx 1 root root  1766 Jul 25 18:16 Identify_junctions_exist_in_certain_number_of_input_files.pl
-rwxrwxrwx 1 root root   581 Jul 25 18:08 JUM_2-1.sh
-rwxrwxrwx 1 root root  2007 Jul 25 13:38 preparing_intron_retention_count_table_short_intron.pl
-rwxrwxrwx 1 root root  3617 Jul 25 13:37 preparing_intron_retention_count_table_long_intron.pl
-rwxrwxrwx 1 root root  1169 Jul 24 19:02 count_intron_read_long_intron_retention_step2_updated.pl
-rwxrwxrwx 1 root root  3145 Jul 24 19:02 determining_rightful_long_intron_retention_event_updated.pl
-rwxrwxrwx 1 root root  2303 Jul 24 19:02 extract_intron_retention_event_coordinate_from_samples_conditional_union.pl
-rwxrwxrwx 1 root root  5098 Jul 24 19:02 final_process_A3SS_output.pl
-rwxrwxrwx 1 root root  5146 Jul 24 19:02 final_process_A5SS_output.pl
-rwxrwxrwx 1 root root  2856 Jul 24 19:02 final_process_cassette_exon_output1.pl
-rwxrwxrwx 1 root root  2856 Jul 24 19:02 final_process_cassette_exon_output1_update.pl
-rwxrwxrwx 1 root root   984 Jul 24 19:02 final_process_cassette_exon_output2.pl
-rwxrwxrwx 1 root root  3977 Jul 24 19:02 final_process_composite_output.pl
-rwxrwxrwx 1 root root  2604 Jul 24 19:02 final_process_IR_output_long.pl
-rwxrwxrwx 1 root root  2253 Jul 24 19:02 final_process_IR_output_short.pl
-rwxrwxrwx 1 root root 10312 Jul 24 19:02 final_process_MXE_output.pl
-rwxrwxrwx 1 root root  1653 Jul 24 19:02 first_processing_generate_JUM_reference_for_profiled_total_alternative_splicing_event_junction.pl
-rwxrwxrwx 1 root root  3250 Jul 24 19:02 generate_JUM_format_annotation_file_for_profiled_alternative_splicing_event_junction.pl
-rwxrwxrwx 1 root root  2572 Jul 24 19:02 identify_gene_name_for_JUM_output_1.pl
-rwxrwxrwx 1 root root  2186 Jul 24 19:02 identify_gene_name_for_JUM_output_2.pl
-rwxrwxrwx 1 root root  1111 Jul 24 19:02 identify_gene_name_for_JUM_output_3.pl
-rwxrwxrwx 1 root root  1446 Jul 24 19:02 Identify_intron_retention_event_exist_in_all_samples.pl
-rwxrwxrwx 1 root root  1691 Jul 24 19:02 Identify_junctions_exist_in_all_samples.pl
-rwxrwxrwx 1 root root  1168 Jul 24 19:02 making_junction_count_file_matching_annotation_for_JUM_in_intron_retention.pl
-rwxrwxrwx 1 root root  1251 Jul 24 19:02 making_junction_count_file_matching_annotation_for_JUM.pl
-rwxrwxrwx 1 root root  1263 Jul 24 19:02 output_reformat_JUM_1.pl
-rwxrwxrwx 1 root root  2880 Jul 24 19:02 output_reformat_JUM_2.pl
-rwxrwxrwx 1 root root  2883 Jul 24 19:02 output_reformat_JUM_3.pl
-rwxrwxrwx 1 root root  2299 Jul 24 19:02 output_reformat_JUM_4.pl
-rwxrwxrwx 1 root root  1225 Jul 24 19:02 prepare_count_file_after_STAR_2_pass_mapping.pl
-rwxrwxrwx 1 root root  2417 Jul 24 19:02 prepare_significant_long_intron_retention_event.pl
-rwxrwxrwx 1 root root  4163 Jul 24 19:02 preparing_intron_retention_event_for_JUM_combine.pl
-rwxrwxrwx 1 root root  6803 Jul 24 19:02 process_raw_AS_differential_output.pl
-rwxrwxrwx 1 root root  2036 Jul 24 19:02 profile_AS_events_sharing_3_prime_ss.pl
-rwxrwxrwx 1 root root  2036 Jul 24 19:02 profile_AS_events_sharing_5_prime_ss.pl
-rwxrwxrwx 1 root root  2738 Jul 24 19:02 profile_overhang_from_STAR_output_step_1.pl
-rwxrwxrwx 1 root root  1689 Jul 24 19:02 profile_overhang_from_STAR_output_step_2.pl
-rwxrwxrwx 1 root root  1496 Jul 24 19:02 profiling_splicing_patterns_from_AS_events_1.pl
-rwxrwxrwx 1 root root  1351 Jul 24 19:02 profiling_splicing_patterns_from_AS_events_2.pl
-rwxrwxrwx 1 root root  8888 Jul 24 19:02 profiling_splicing_patterns_from_AS_events_3_updated.pl
-rwxrwxrwx 1 root root  1686 Jul 24 19:02 profiling_splicing_patterns_from_AS_events_4.pl
-rwxrwxrwx 1 root root  2424 Jul 24 19:02 profiling_splicing_patterns_from_AS_events_5.pl
-rwxrwxrwx 1 root root  2461 Jul 24 19:02 profiling_splicing_patterns_from_AS_events_6.pl
-rwxrwxrwx 1 root root  3317 Jul 24 19:02 profiling_splicing_patterns_from_AS_events.pl
-rwxrwxrwx 1 root root  1106 Jul 24 19:02 R_script_JUM.R
-rwxrwxrwx 1 root root  1861 Jul 24 19:02 screening_A5SS_A3SS_events.pl
-rwxrwxrwx 1 root root  3082 Jul 24 19:02 screening_cassette_exon_events.pl
-rwxrwxrwx 1 root root  2161 Jul 24 19:02 screening_intron_retention_event_for_deltachange_consistency.pl
-rwxrwxrwx 1 root root  1831 Jul 24 19:02 screening_intron_retention_event_for_no_inner_junction.pl
-rwxrwxrwx 1 root root  5090 Jul 24 19:02 screening_MXE_events.pl
-rwxrwxrwx 1 root root  1698 Jul 24 19:02 second_processing_generate_JUM_reference_for_profiled_total_alternative_splicing_event_junction.pl
-rwxrwxrwx 1 root root   592 Jul 24 19:02 vary_for_replicate.pl
-rwxrwxrwx 1 root root  1435 Jul 24 19:02 count_reads_for_intron_retention_sam.pl
-rwxrwxrwx 1 root root  2052 Jul 24 19:02 determining_rightful_total_cassette_exon_event.pl
-rwxrwxrwx 1 root root    65 Jul 24 19:02 experiment_design.txt
-rwxrwxrwx 1 root root  4929 Jul 24 19:02 extract_intron_retention_event_coordinate_conditional_union_splicing_junction_gff.pl
-rwxrwxrwx 1 root root  1549 Jul 24 19:02 count_intron_read_long_intron_retention_step1.pl
-rwxrwxrwx 1 root root  1350 Jul 24 19:02 count_intron_read_long_intron_retention_step3.pl
root@debian:/mnt/hgfs/rawdata/fastq/JUM#

**Comment by qqwang-berkeley** [comment]
I see that you are still running the old command style for JUM.

Starting from JUM_2.0.2, you should run JUM with JUM_A.sh, JUM_B.sh, and
JUM_C.sh (instead of JUM_2-1.sh, JUM_2-2.sh etc.)
Please see this tutorial:
https://github.com/qqwang-berkeley/JUM/wiki/3.1.-Manual-running-JUM-(v2.0.2-and-up)

Could you run JUM_A.sh as shown in the manual above and let me know if
it works? (Here JUM_A.sh did all the substeps for you and changed the way
parameters are fed to the subcommands)

**Comment by LOYON2019** [comment]
Hi, thanks for the response, I got a new issue.  see below  "bash: JUM/JUM_2-2.sh: No such file or directory"

root@debian:/mnt/hgfs/rawdata/fastq# bash JUM/JUM_A.sh --Folder JUM --JuncThreshold 5 --Condition1_fileNum_threshold 3 --Condition2_fileNum_threshold 3 --IRthreshold 5 --Readlength 150 --Thread 3 --Condition1SampleName N2S1,N2S2,N2S3 --Condition2SampleName N2F1,N2F2,N2F3
Sample names are:
N2S1
N2S2
N2S3
N2F1
N2F2
N2F3
bash: JUM/JUM_2-2.sh: No such file or directory
root@debian:/mnt/hgfs/rawdata/fastq#

**Comment by qqwang-berkeley** [comment]
OK, Now I see what is going on.

Yes the errors you have encountered is because during the latest upgrade of JUM
2.0.2, I used a user-provided argument management function that is only
compatible to newer versions of the Linux system. It is not compatible with
Mac OSX that is BSD-derived, and likely for earlier versions of Linux.  So
basically, the folder name, file name, threshold etc. you fed JUM is not
accepted by Linux so that is why you have been having issues.

I have generated a modified version of JUM2.0.2 (see attached) that
bypasses the fancy user argument function but go back to the old and
classic (although a bit dull) one that was used in JUM 2.0, and is stable
and compatible with all versions of Linux as well as Mac OSX.

You can follow everything as on the manual, except that you should ignore
the descriptions for parameters such as "--Folder" etc for all three
JUM_A.sh/JUM_B.sh/JUM_C.sh scripts; instead just simply give the
parameters.  For example, you need to run JUM_A.sh as:

bash /user/home/JUM_2.0.2/JUM_A.sh /user/home/JUM_2.0.2 5 2 2 5 100 3
ctrl1,ctrl2,ctrl3 treat1,treat2,treat3

Just be careful that you include all the input parameters and they are in
the right order (9 parameters for JUM_A.sh, 8 for JUM_B.sh and 6 for
JUM_C.sh - this is the reason I updated the user input to the fancy new
system which is not compatible with mac or older versions of linux... to
help users ease the process of parameter feeding).

Please let me know if this version works for you and if you have any
questions. I will need to add this version to the GitHub page.

Qingqing

**Comment by LOYON2019** [comment]
Hi Qingqing,
thanks for the help, you are right, I use Debian 8. could you let me where I can get the modified version of JUM2.0.2? 
thank you.

**Comment by qqwang-berkeley** [comment]
I attached it with the previous email. Did you get it? If not, I will send
it again.

**Comment by qqwang-berkeley** [comment]
OK. I have uploaded the package to the JUM GitHub page.

Check here:
https://github.com/qqwang-berkeley/JUM/releases/tag/JUMv2.0.2_short_user_argument_BSD

**Comment by qqwang-berkeley** [comment]
this is really bizarre. You checked that JUM_2-2.sh is in
the :/mnt/hgfs/rawdata/fastq/JUM directory, right?

What about providing the full path of /mnt/hgfs/rawdata/fastq/JUM as the
first parameter when running JUM_A.sh (the path for all JUM scripts)?

**Comment by qqwang-berkeley** [comment]
Just want to quickly follow up. Did JUM work for you now?
