### ISSUE TITLE
second pass STAR

### ISSUE THREAD

**Issue by lindongdo** [qqwang-berkeley/JUM#22]

**Comment by lindongdo** [comment]
Hi,
I am running JUM the latest version 2.0.2 by following the manual https://github.com/qqwang-berkeley/JUM/wiki/3.1.-Manual-running-JUM-(v2.0.2-and-up), which looks different to previous 2.0 version especially in inputs. There are two passes of STAR mapping in previous version but I couldn't find it in the latest version manual. Do we still need to follow previous pipeline to run two passes of STAR as the input in the latest version?

Thanks

Dong

**Comment by qqwang-berkeley** [comment]
Hi,

I changed the two passes of STAR for input from v2.0 to just one round in
v2.0.2 because STAR now integrates two passes of mapping into one round
during a recent upgrade . You can simply follow the instructions in the
latest version. It is just easier - one step less.

Best,

Qingqing
