### ISSUE TITLE
Tons of stderr output; problem with preparing_intron_retention_count_table_short_intron.pl

### ISSUE THREAD

**Issue by acesnik** [qqwang-berkeley/JUM#23]
Hi there! I'm excited to use your tool and am testing it out.

With some test files, I'm getting about 4,000,000 lines of stderr output like this:

```
Use of uninitialized value $readlength in numeric lt (<) at /home/JUM_2.0.2/profile_overhang_from_STAR_output_step_1.pl line 39, <IN1> line 1.
Use of uninitialized value $readlength in subtraction (-) at /home/JUM_2.0.2/profile_overhang_from_STAR_output_step_1.pl line 43, <IN1> line 1.
Use of uninitialized value $readlength in numeric lt (<) at /home/JUM_2.0.2/profile_overhang_from_STAR_output_step_1.pl line 45, <IN1> line 1.
Use of uninitialized value $readlength in subtraction (-) at /home/JUM_2.0.2/profile_overhang_from_STAR_output_step_1.pl line 49, <IN1> line 1.
Use of uninitialized value $readlength in numeric lt (<) at /home/JUM_2.0.2/profile_overhang_from_STAR_output_step_1.pl line 39, <IN1> line 2.
Use of uninitialized value $readlength in subtraction (-) at /home/JUM_2.0.2/profile_overhang_from_STAR_output_step_1.pl line 43, <IN1> line 2.
Use of uninitialized value $readlength in numeric lt (<) at /home/JUM_2.0.2/profile_overhang_from_STAR_output_step_1.pl line 45, <IN1> line 2.
Use of uninitialized value $readlength in subtraction (-) at /home/JUM_2.0.2/profile_overhang_from_STAR_output_step_1.pl line 49, <IN1> line 2.
Use of uninitialized value $readlength in numeric lt (<) at /home/JUM_2.0.2/profile_overhang_from_STAR_output_step_1.pl line 39, <IN1> line 3.
Use of uninitialized value $readlength in subtraction (-) at /home/JUM_2.0.2/profile_overhang_from_STAR_output_step_1.pl line 43, <IN1> line 3.
Use of uninitialized value $readlength in numeric lt (<) at /home/JUM_2.0.2/profile_overhang_from_STAR_output_step_1.pl line 45, <IN1> line 3.
Use of uninitialized value $readlength in subtraction (-) at /home/JUM_2.0.2/profile_overhang_from_STAR_output_step_1.pl line 49, <IN1> line 3.
```

and this:

```
Use of uninitialized value $threshold in numeric ge (>=) at /home/JUM_2.0.2/preparing_intron_retention_count_table_long_intron.pl line 73.
Use of uninitialized value $threshold in numeric ge (>=) at /home/JUM_2.0.2/preparing_intron_retention_count_table_long_intron.pl line 73.
Use of uninitialized value $threshold in numeric ge (>=) at /home/JUM_2.0.2/preparing_intron_retention_count_table_long_intron.pl line 73.
Use of uninitialized value $threshold in numeric ge (>=) at /home/JUM_2.0.2/preparing_intron_retention_count_table_long_intron.pl line 73.
Use of uninitialized value $threshold in numeric ge (>=) at /home/JUM_2.0.2/preparing_intron_retention_count_table_long_intron.pl line 73.
Use of uninitialized value $threshold in numeric ge (>=) at /home/JUM_2.0.2/preparing_intron_retention_count_table_long_intron.pl line 73.
Use of uninitialized value $threshold in numeric ge (>=) at 
```

and then it fails with:

```
can't open input1 file: No such file or directory at /home/JUM_2.0.2/preparing_intron_retention_count_table_short_intron.pl line 18.
```

Any help would be appreciated. Thanks!

**Comment by acesnik** [comment]
In terms of setup, I did two-pass alignment with STAR, sorted the BAM files, converted them to SAM files to have those around, and changed the names of the files to follow your naming conventions.

**Comment by qqwang-berkeley** [comment]
Hi Anthony,

Could you provide me the commands you used, and also, the results of
running "ls -l -t" from the directory where you ran JUM?

Thanks,

Qingqing

**Comment by acesnik** [comment]
`/home/tools/JUM_2.0.2/JUM_A.sh --Folder /home/tools/JUM_2.0.2 --JuncThreshold 5 --Condition1SampleName G1_1.,G1_2.,G1_3. --Condition1_fileNum_threshold 2 --Condition2SampleName S_1.,S_2.,S_3. --Thread 2`

I'm attaching the listed files here:
[lslt.txt](https://github.com/qqwang-berkeley/JUM/files/3527606/lslt.txt)

Thanks!

**Comment by acesnik** [comment]
I used `samtools view -h /home/output/JUM_Analysis/G_1.Aligned.out_sorted.bam > /home/output/JUM_Analysis/G_1.Aligned.out.sam` to get the SAM files for the tool. I output sorted BAMs by default from STAR, so I had to convert them.

**Comment by qqwang-berkeley** [comment]
From the command it looks like you did not specify a couple specific
parameters:


Your original command
/home/tools/JUM_2.0.2/JUM_A.sh --Folder /home/tools/JUM_2.0.2
--JuncThreshold 5 --Condition1SampleName G1_1.,G1_2.,G1_3.
--Condition1_fileNum_threshold 2 --Condition2SampleName S_1.,S_2.,S_3.
--Thread 2

should be:
/home/tools/JUM_2.0.2/JUM_A.sh --Folder /home/tools/JUM_2.0.2
--JuncThreshold 5 *--Condition1_fileNum_threshold X
--Condition2_fileNum_threshold X --IRthreshold X --Readlength X* --Thread 2
--Condition1SampleName G1_1.,G1_2.,G1_3. --Condition1_fileNum_threshold 2
--Condition2SampleName S_1.,S_2.,S_3.

*X will a user chosen number.*

**Comment by acesnik** [comment]
Okay, that fixed this issue. I think the main thing that was missing from my command was IRthreshold.
