### ISSUE TITLE
can --Condition1_fileNum_threshold and  --Condition2_fileNum_threshold be unequal?

### ISSUE THREAD

**Issue by itszhengan** [qqwang-berkeley/JUM#28]
Can --Condition1_fileNum_threshold  and  --Condition2_fileNum_threshold be unequal? I mean maybe we have 3 disease samples and 2 normal samples, or 20 disease samples and 40 normal samples (all the samples have no replicate).

**Comment by qqwang-berkeley** [comment]
Yes they can totally be unequal. Set them up as your experimental design.

**Comment by itszhengan** [comment]
> Yes they can totally be unequal. Set them up as your experimental design.

Thank you and I'll try it later.
