### ISSUE TITLE
How to match sub-junctions to PSI value in composite events?

### ISSUE THREAD

**Issue by angel-bee2018** [qqwang-berkeley/JUM#32]
Hi,

For composite events which contain a very high number of sub-junctions, we often get multiple PSI values. How do we know which sub-junctions each of the PSI values refer to? 

In other words, how do we determine the local exon connectivity associated with each PSI value? There is no explicit information in the output tables about this.

I've looked at the AS_structure_ID in the detailed tables, but they all seem to describe junctions contributing to A3SS or A5SS. But there doesn't ever seem to be splice junctions that are characteristic of cassette exon or MXE, even though there clearly is a cassette event (as determined from IGV and other AS detection programs). Not sure if this is a bug? Could you please advise whether JUM is able to consider all of A3SS, A5SS, cassette exon, MXE and IR (where observed) in the composite events category?

Thanks

**Comment by qqwang-berkeley** [comment]
Hi,

Could you give an example of what you meant?

Qingqing

**Comment by angel-bee2018** [comment]
closing because i figured out the composite event junctions reflect LSVs.
