### ISSUE TITLE
Can JUM be run on a single bam file ( only one treatment bam or only one control bam)

### ISSUE THREAD

**Issue by itszhengan** [qqwang-berkeley/JUM#34]
Hi,

Can JUM be run on a single bam file ( only one treatment bam or only one control bam)? What if I just want to get the gene corresponding splicing event and psi value? Thank you.

**Comment by lhdo** [comment]
Instructions from the author for single sample run is detailed here:

https://github.com/qqwang-berkeley/JUM/wiki/4.2.-Workaround-if-you-do-not-have-biological-replicates-(version-2.0.2-)

**Comment by itszhengan** [comment]
> Instructions from the author for no replicate sample run is detailed here:
> 
> https://github.com/qqwang-berkeley/JUM/wiki/4.2.-Workaround-if-you-do-not-have-biological-replicates-(version-2.0.2-)


Thank you for your reply. But it seems that you may misunderstand it. The manual only tells what to do when missing replicate samples but not only one condition(without control). I just want to get one sample's psi for each splicing event. Could "--Condition2_fileNum_threshold" be set to 0 when we only want to get one sample's result?

**Comment by lhdo** [comment]
I see. It seems then that you just want the PSI values for each condition as well, which is what I also want to calculate and have asked the author (issue above yours). Running only one sample may not be currently possible, but if you could calculate PSI values for each condition (not delta PSI), it would suit your purpose.

**Comment by itszhengan** [comment]
> I see. It seems then that you just want the PSI values for each condition as well, which is what I also want to calculate and have asked the author (issue above yours). Running only one sample may not be currently possible, but if you could calculate PSI values for each condition (not delta PSI), it would suit your purpose.

Thank you. It seems that we can only wait for author's reply.

**Comment by qqwang-berkeley** [comment]
Hi, Sorry for the late reply. If you just want to get the gene corresponding splicing event and psi value with one sample, one way to do it is to copy your single bam file, and re-named it as it it were a different file (copy as many as you want, for both condition 1 and condition 2 reps), and feed them to JUM, run through the original pipeline, but set pvalue to 1 in the last step. In that case you will have a full atlas of splicing events profiled from the sample bam file.

**Comment by itszhengan** [comment]
> Hi, Sorry for the late reply. If you just want to get the gene corresponding splicing event and psi value with one sample, one way to do it is to copy your single bam file, and re-named it as it it were a different file (copy as many as you want, for both condition 1 and condition 2 reps), and feed them to JUM, run through the original pipeline, but set pvalue to 1 in the last step. In that case you will have a full atlas of splicing events profiled from the sample bam file.

Thank you so much. I'll try it.
