### ISSUE TITLE
PSI values per condition

### ISSUE THREAD

**Issue by lhdo** [qqwang-berkeley/JUM#35]
How would I go about calculating the PSI values per condition (i.e. PSI for control and PSI for treatment) for each event type? Currently, I only see the delta PSI values reported from both the simplified and detailed output files. Any help would be greatly appreciated! Thanks!

**Comment by qqwang-berkeley** [comment]
Hi, sorry for the late reply. If you want to calculate the PSI value per condition, one work around is to check the following columns in the detailed output files:
raw_count.ctrl1
raw_count.ctrl2
raw_count.ctrl3
raw_count.treat1
raw_count.treat2
raw_count.treat3
percentage_usage.ctrl1
percentage_usage.ctrl2
percentage_usage.ctrl3
percentage_usage.treat1
percentage_usage.treat2

These columns record the raw counts to each sub_AS_junction in every AS_structure (for the definition of AS structure, please refer to the JUM manuscript), and if you refer to the manual about the definition of PSI for each event type (detailed in the "output" part in the manual), you should be able to calculate the PSI values per condition. These values are put there to give users an idea about the raw outcome as well.
