### ISSUE TITLE
Recommendations for sequencing depth

### ISSUE THREAD

**Issue by krisscrim** [qqwang-berkeley/JUM#37]
Hi, do you have recommendations for the number of aligned reads to genes? Is it possible to make JUM work with < 20M aligned reads mapping to mRNA/sample?

Also, do you recommend Poly-A or ribodepletion libraries for analysis with JUM?

**Comment by qqwang-berkeley** [comment]
Hi,

Depending on your organism. For drosophila, 20M should be enough. For humans, I would recommend >20-30M.

poly-A or ribodepletion are both fine. I have used JUM to analyze both libraries. Just note, for the ribodepeletion library the quality will vary based on the experimental execution, as the ribos may not be completely depleted from time to time. But you can tell right away from the mapping step, as the ones mapped to ribos will be multi-mapped and you should be able to check the ratio v.s. uniquely mapped.

Qingqing
