### ISSUE TITLE
JUM output Splicing events Visualization tools

### ISSUE THREAD

**Issue by shashibioinfo143** [qqwang-berkeley/JUM#38]
Hi all,

greetings.

I was working on mRNA Splicing event analysis. I was using the JUM tool for mRNA splicing which gives 6 categories of splice patterns

for Visualizing these splice events I was looking for tools, came across IGV, LeafViz.

LeafViz is a Shiny app that is more interactive needs more scripting the inputs. moreover, LeafViz is part of Leafcutter it didn't accept other format files. I have started using LeafViz for JUM output files and I have troubleshooting errors that I encountered.

if anyone please let us know if it's possible to use JUM output files in Leafviz for the Visualization of splicing events or else please mention tools that are most useful for Visualization of Splice events.

Hope to hear good suggestions.

Thank you

**Comment by qqwang-berkeley** [comment]
Hi,

You can use iGV to visualize the splicing events identified by JUM, just
simply feed iGV with your 2nd pass mapping bam files.

If you would like JUM to provide an output file compatible with LeafViz,
could you send me a sample input file for LeafViz? I will add a code in the
package to re-format a version of JUM output.

Qingqing
