### ISSUE TITLE
JUM (v2.0.2 and up) stops and get killed at a certain step

### ISSUE THREAD

**Issue by farzaneafzali** [qqwang-berkeley/JUM#40]
Hi,
The JUM_A.bash  stops and get killed at this step:

```
    process_sortedbam () {
    sortfile=$1;
    bamfiletobed=${sortfile%_sorted.bam}.bed;
    bamsortedbed=${sortfile%_sorted.bam}.sorted.bed;
    intersect_bam_long_intron=${sortfile%_sorted.bam}"_"intersect_long_intron.txt;
    intersect_bam_short_intron1=${sortfile%_sorted.bam}"_"intersect_short_intron1.txt;
    intersect_bam_short_intron2=${sortfile%_sorted.bam}"_"intersect_short_intron2.txt;
    bedtools bamtobed -i $sortfile > $bamfiletobed;
    sort -k1,1 -k2,2n $bamfiletobed > $bamsortedbed;
    intersectBed -a $bamsortedbed -b output_long_intron_sorted.gff -sorted -wa -u -f 1 > $intersect_bam_long_intron 
    intersectBed -a $bamsortedbed -b output_short_intron1_sorted.gff -sorted -wa -u -f 1 > $intersect_bam_short_intron1 
    intersectBed -a $bamsortedbed -b output_short_intron2_sorted.gff -sorted -wa -u -F 1 > $intersect_bam_short_intron2 
}
```
Exact error:
`Killed                sort -k1,1 -k2,2n $bamfiletobed > $bamsortedbed`

 I'm guessing it might be a CPU error as it gets killed but more than that, not sure. I'm working with a 16 threads system and once used all and other times just 14 of them, but it gets killed anyway. 
Code I'm using:
`bash /path/JUM_2.0.2_multi/JUM_A.sh --Folder /path/JUM_2.0.2_multi --JuncThreshold 5 --Condition1_fileNum_threshold 2 --Condition2_fileNum_threshold 2 --IRthreshold 5 --Readlength 101 --Thread 16 --Condition1SampleName cntrl1,cntrl2,cntrl3 --Condition2SampleName treat1,treat2,treat3`

Does anyone know what might be wrong and how can I fix it please? 
Thanks.

**Comment by qqwang-berkeley** [comment]
Hi,

There are two possibilities:

1) the RAM can not handle the parallel processing mode of JUM_A.
2) there is not enough space in /tmp directory on your working
computer/cluster for the sort command.

Both issues can be solved. let's try one first. For now, could you try the
attached modified JUM_A.sh script and let me know if it solves the issue
(just run the JUM_A_non_parallel.sh attached exactly as you run JUM_A.sh.
It is just the name of the script is different.)?

Let me know.

Best,

Qingqing

**Comment by farzaneafzali** [comment]
Hi Qingqing,
Thanks for replying back. I just can't find your attached file. Neither here nor in email. Maybe it didn't come through?! 

Best,
Farzaneh

**Comment by farzaneafzali** [comment]
Hi @qqwang-berkeley 
Can you please send the script again? I can't find it. Thanks so much

**Comment by qqwang-berkeley** [comment]
Could you please provide a personal email address? Turns out that I can’t
attach files with the GitHub address. Thank you!

**Comment by farzaneafzali** [comment]
@qqwang-berkeley  Of course. Here it is: 
farzaneafzali@gmail.com

Thank you!

**Comment by farzaneafzali** [comment]
@qqwang-berkeley Hi Qingqing, Just wanted to update you that this part finished successfully with non-parallel code. 
Thanks so much for your help,
Farzaneh
