### ISSUE TITLE
Regarding delta-PSI value, control-treatment vs treatment-control

### ISSUE THREAD

**Issue by varamhcu** [qqwang-berkeley/JUM#47]
I have a query regarding the resultant delta-Psi value. 

After running the JUM_C.sh, deltaPSI value is provided for control-treatment.

Can we calculate the deltaPSI value for treatment-Control ? 

Thank you

**Comment by qqwang-berkeley** [comment]
if you want to get the deltaPSI for the other way round, just do 0-deltaPSI_for_the_provided_control-treatment. They are simply of the opposite sign.
