### ISSUE TITLE
Regarding Error "NONE" after running JUM_C.sh

### ISSUE THREAD

**Issue by heebaanjum** [qqwang-berkeley/JUM#48]
Hello everyone,

After running JUM_C.sh, the output files from FINAL_JUM_OUTPUT_pvalue_0.05, have all the identified events as "NONE". Not even single event is annotated to transcript_id. Please help me to figure out what exactly is the error, because atleast some of the events should be annotated to a gene or transcript id. 

I have attached below first 10 lines of genePred file used for --REF argument.
[MSU_v7_genepred_first_10_lines.txt](https://github.com/qqwang-berkeley/JUM/files/10954235/MSU_v7_genepred_first_10_lines.txt)

Could you please help me to troubleshoot this?
Thank you so much

**Comment by qqwang-berkeley** [comment]
Your gene annotation format is wrong. Please make sure that it is compatible with the refFlat file format. Something like:
ZNF639	NM_001375803	chr3	+	179323030	179338583	179328293	179334422	5	179323030,179328282,179329617,179332988,179333268,	179323291,179328351,179329728,179333123,179338583,
WASH7P	NR_024540	chr1	-	14361	29370	29370	29370	11	14361,14969,15795,16606,16857,17232,17605,17914,18267,24737,29320,	14829,15038,15947,16765,17055,17368,17742,18061,18366,24891,29370,
MIR6859-1	NR_106918	chr1	-	17368	17436	17436	17436	1	17368,	17436,
MIR6859-2	NR_107062	chr1	-	17368	17436	17436	17436	1	17368,	17436,
